"""update__table

Revision ID: 1ff6887631dd
Revises: 36e599e5d722
Create Date: 2026-08-06 03:08:14.129751

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ff6887631dd'
down_revision: Union[str, Sequence[str], None] = '36e599e5d722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_bundle', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('user', sa.Column('vault', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vault')
    op.drop_column('user', 'public_bundle')
    # ### end Alembic commands ###
