"""update_tables

Revision ID: 36e599e5d722
Revises: e57db56da13d
Create Date: 2026-08-05 22:11:32.070942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e599e5d722'
down_revision: Union[str, Sequence[str], None] = 'e57db56da13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('session_user_id_key'), 'session', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('session_user_id_key'), 'session', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
