"""update_user_table

Revision ID: e57db56da13d
Revises: 3b0caad7918d
Create Date: 2026-08-05 18:05:37.710982

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e57db56da13d'
down_revision: Union[str, Sequence[str], None] = '3b0caad7918d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('auth_token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('user_ip', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('device_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('user', sa.Column('password_hash', sa.LargeBinary(), nullable=False))
    op.drop_column('user', 'kdf_salt')
    op.drop_column('user', 'auth_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('kdf_salt', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('user', 'password_hash')
    op.drop_table('session')
    # ### end Alembic commands ###
